server:
  port: 9096


spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatSql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop


  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:messages
    username: batman
    password: robin
    driver-class-name: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #holds a comma-seperated list of eureka services this service will use
      #to resolve locations
      default-zone: http://localhost:8761/eureka